// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'high-contrast-light', 'high-contrast-dark', 'bw-light', 'bw-dark']
    }
}

export {}
