/* eslint-disable unicorn/filename-case, @typescript-eslint/no-explicit-any, @typescript-eslint/ban-ts-comment, import/first */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ApiSearchRouteImport } from "./routes/api/search";
import { Route as DocsSplatRouteImport } from "./routes/docs/$";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LlmsFullDottxtRouteImport } from "./routes/llms-full[.]txt";
import { Route as LlmsDotmdxDocsSplatRouteImport } from "./routes/llms[.]mdx.docs.$";
import { Route as LlmsDottxtRouteImport } from "./routes/llms[.]txt";

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/llms.txt",
  path: "/llms.txt",
} as any);
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/llms-full.txt",
  path: "/llms-full.txt",
} as any);
const IndexRoute = IndexRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/",
  path: "/",
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/docs/$",
  path: "/docs/$",
} as any);
const ApiSearchRoute = ApiSearchRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/api/search",
  path: "/api/search",
} as any);
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/llms.mdx/docs/$",
  path: "/llms.mdx/docs/$",
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/llms.mdx/docs/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/llms.mdx/docs/$";
  id:
    | "__root__"
    | "/"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/llms.mdx/docs/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute;
  LlmsDottxtRoute: typeof LlmsDottxtRoute;
  ApiSearchRoute: typeof ApiSearchRoute;
  DocsSplatRoute: typeof DocsSplatRoute;
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/llms.txt": {
      id: "/llms.txt";
      path: "/llms.txt";
      fullPath: "/llms.txt";
      preLoaderRoute: typeof LlmsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/llms-full.txt": {
      id: "/llms-full.txt";
      path: "/llms-full.txt";
      fullPath: "/llms-full.txt";
      preLoaderRoute: typeof LlmsFullDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/docs/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/search": {
      id: "/api/search";
      path: "/api/search";
      fullPath: "/api/search";
      preLoaderRoute: typeof ApiSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/llms.mdx/docs/$": {
      id: "/llms.mdx/docs/$";
      path: "/llms.mdx/docs/$";
      fullPath: "/llms.mdx/docs/$";
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  IndexRoute: IndexRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
